apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-alpine-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nginx
              image: nginx:alpine
              command:
                [
                  "sh",
                  "-c",
                  "nginx -g 'daemon off;' & sleep 10 && curl localhost",
                ]
          restartPolicy: OnFailure
