apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine
  labels:
    app: ktl-ai
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3
