apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine-resource
  labels:
    app: ktl-ai
spec:
  containers:
    - image: nginx:alpine
      name: nginx

      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3

      readinessProbe:
        httpGet:
          path: /
          port: 80
        periodSeconds: 2
        initialDelaySeconds: 0
        failureThreshold: 3
        successThreshold: 1

      ports:
        - containerPort: 80
          name: http

      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
