apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine-secret
  labels:
    app: ktl-ai
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config
          mountPath: "/etc/nginx-secrets"
          readOnly: true
  volumes:
    - name: nginx-config
      secret:
        secretName: nginx-secret
